// Code generated by tygo. DO NOT EDIT.

//////////
// source: player.go
/*
Package player owns the torrent client and streams playback sources as
seekable HTTP: torrents stream their largest file directly via
http.ServeContent (mpv's Range requests just work, no transcoding
involved), and direct-URL sources get a redirect straight to the origin.
A background reaper (CleanupTorrents) drops idle torrents and their
on-disk pieces after 30 minutes of no active readers, so a long-running
process doesn't accumulate downloaded data forever.
*/

/**
 * Player owns all of the package's mutable state — the torrent client and the
 * active-torrent registry — plus the injected TMDB client and addon manager.
 * Fields are unexported, so tygo emits nothing for Player.
 */
export interface Player {
}
